name: Deployment
run_name: Checking the push of the new code.

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: echo 'push went well.'
        # ...deployment-specific steps
